### ISSUE TITLE
test accounts-google

### ISSUE THREAD

**Issue by splendido** [splendido/meteor-accounts-emails-field#28]

**Comment by steph643** [comment]
I believe it is not possible to create a Google account without a verified email anymore.

Here is what can be seen in https://accounts.google.com/SignUpWithoutGmail:

![image](https://cloud.githubusercontent.com/assets/7039479/7909931/964d7dc8-0850-11e5-8bb2-2b1883bbe9f4.png)

Even after providing and verifying a mobile phone number, Google asks you this:

![image](https://cloud.githubusercontent.com/assets/7039479/7909945/b5101676-0850-11e5-82c7-40cb76dfc460.png)

If this is confirmed, the doc shouldn't have the "let non-verified in" cross for Google.

**Comment by splendido** [comment]
Yeah, agreed!
Please try to access into an app using `accounts-meld` before concluding the verification process...
