### ISSUE TITLE
Export updateEmails and getEmailFromService

### ISSUE THREAD

**Issue by rbabayoff** [splendido/meteor-accounts-emails-field#36]
So they can be called for all users that were created before this package was installed. How about exporting:

```
AccountEmails.updateEmails
AccountEmails.getEmailFromService
```

**Comment by splendido** [comment]
A little late, sorry!

See [Advanced API](https://github.com/splendido/meteor-accounts-emails-field/#advanced-api) and [v1.2.0](https://github.com/splendido/meteor-accounts-emails-field/releases/tag/v1.2.0)
