### ISSUE TITLE
Function to update registered emails for all existing users

### ISSUE THREAD

**Issue by rbabayoff** [splendido/meteor-accounts-emails-field#37]
To maintain data consistency with accounts that were created before package was installed.

**Comment by splendido** [comment]
A little late, sorry!

See [Advanced API](https://github.com/splendido/meteor-accounts-emails-field/#advanced-api) and [v1.2.0](https://github.com/splendido/meteor-accounts-emails-field/releases/tag/v1.2.0)

**Comment by rbabayoff** [comment]
No worries :)
